### ISSUE TITLE
'mastodon' or 'Mastodon'

### ISSUE THREAD

**Issue by jorgesumle** [L1am0/mastodon_wordpress_autopost#10]
While I was translating this plugin into Spanish, I noticed that you say both 'mastodon' (with lowercase) and 'Mastodon' (with uppercase). In the [article of Wikipedia](https://en.wikipedia.org/wiki/Mastodon_(software)), they always use the uppercase. I assume they do that because Mastodon is a proper name. Is there something I'm missing. If not, let me know. I can submit a pull request to fix it.

**Comment by L1am0** [comment]
oh thanks for checking that!
Would be so nice if you could do a pullrequest for that :D

**Comment by jorgesumle** [comment]
Solved in #11

**Comment by L1am0** [comment]
Thanks for your help!
