### ISSUE TITLE
Syndication URL returned for possible display?

### ISSUE THREAD

**Issue by chrisaldrich** [L1am0/mastodon_wordpress_autopost#4]
If Mastodon returns the permalink for the syndicated copy of the post, it would be nice if this plugin would store/provide that data so that plugins like https://github.com/dshanske/syndication-links could potentially display where copies of the post went.

A sample of the UI can be seen here: http://boffosocko.com/2017/10/25/testing-syndication-to-mastodon-from-wordpress/

**Comment by L1am0** [comment]
Hey  chrisaldrich,
sorry for replying so late. I have seen the issue just right now (Why the hell does github don't send emails for new issues :/)

I read now for about half an hour about syndication but still don't get it.
What is it use for?

Would it help, if the plugin displays the Post URL? So that in the "Successfully posted" message, also a the URL is included?

Thanks for help,
L1am0

**Comment by L1am0** [comment]
The 2.0 update shipping tomorrow attaches a new key to the post metadata: "mastodonAutopostLastSuccessfullPostURL"
This key contains the url of the last toot. 
I hope this is what you where asking for.

**Comment by chrisaldrich** [comment]
Thanks @L1am0, I'm suspecting that this should work to help close the loop.  

Since I would guess you'd use it all and for a clearer explanation for the reasons for this, it might help to look at the similar but more fully fleshed out and working birdsite (aka Twitter) example which goes like this:

1. I post a status update to my WordPress Website
2. Using a tool similar to Mastodon Autopost, I syndicate a copy of that update to Twitter which includes a permalink of my WP post.
3. I store the URL of the Twitter copy using [Syndication Links](https://github.com/dshanske/syndication-links) which includes a microformat class of `u-syndication` on the Twitter permalink. (This could be done manually, but it's far easier/quicker automating it with Syndication Links plugin).
4. The free 3rd party service [Bridgy](https://brid.gy/about) watches both my WordPress site and my Twitter account and sends my WP site notifications of replies, comments, and likes using the [Webmention protocol](https://www.w3.org/TR/webmention/). It does this by being able to match the copies of my posts up via my WP permalinks and the `u-syndication` tagged URL on that post to the Twitter version.

The end result is that I own all the content I publish on my WordPress site and simultaneously I can cross post to other social silos which can now communicate back to my original posts. In the end, ideally, a full transcript of the conversation that happens around my content ends up on my website.

As an example, you can look at this post: [The Facebook Algorithm Mom Problem](http://boffosocko.com/2017/07/11/the-facebook-algorithm-mom-problem/) which I syndicated to [several other locations](http://boffosocko.com/2017/07/11/the-facebook-algorithm-mom-problem/#Syndicated+copies+to). You'll see many of the [responses to my WP post](http://boffosocko.com/2017/07/11/the-facebook-algorithm-mom-problem/#responses%20on) were not posted to my native comment section, but were instead backfed from Twitter, Facebook, etc. via Brid.gy and or other sites which support Webmention. In the end, the majority of the conversation is stored on my site. Sadly none of it is built out for Hacker News or the volume would be double, though by clicking on the Hacker News Icon in the syndicated section will allow one to see that portion of the conversation (at least as long as that site stays up).

A large group of people (many under the banners of [IndieWeb](https://indieweb.org), the [Social Group of the W3C](https://www.w3.org/wiki/Socialwg), and surely many other independents) are working at better federating pieces of the internet so that websites can talk to each other in a more coordinated and decentralized fashion. Your fix should help close out half of 3 on the list, we'll just need to finish out 4 which is [documented here](https://github.com/snarfed/bridgy#adding-a-new-silo).

I'll also note that the [creator of Bridgy](https://github.com/snarfed) also has a [FedBridgy service](https://fed.brid.gy/) which is working at the entirety of the problem from a different perspective leveraging the built in plumbing of Mastodon. Another separate alternative would be for Mastodon to support[ sending/receiving Webmentions natively](https://github.com/tootsuite/mastodon/issues?q=is%3Aissue+webmention+is%3Aopen).

Hopefully this "short" description helps. If you're curious about more, I'm happy to help point you to resources for additional details and/or help. 

Thanks for building Mastodon Autopost!!

**Comment by dshanske** [comment]
Just discovered this has broken, as you changed it to mastodonAutopostLastSuccessfullTootURL Looking for both now.
