### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by scroom** [L1am0/mastodon_wordpress_autopost#6]
Hi,

I just updated to version 2.0.0.1 and tried to complete the settings. But the OAuth seems not to work. I get the following message from my mastodon instance:

`Client-Authentifizierung ist fehlgeschlagen: Client unbekannt, keine Authentisierung mitgeliefert oder Authentisierungsmethode wird nicht unterstützt. `

**Comment by L1am0** [comment]
The authentication bug is fixed in version 2.0.0.2

This sort of bugs will not happen again in the future. 
I started to test with different instances to prevent this stuff in the future.

My bad that till now I only tested with mastodon.social.

Sorry mate.

BR,
L1am0
