### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by scroom** [L1am0/mastodon_wordpress_autopost#7]
The OAuth error seems to be resolved. An Auth-code is requested and I get no error message after copying this code in the window and clicking OK.

But if I'm testing the configuration ("Einstellungen testen") I get the following error message:

`Unbekannter Mastodon Error! Bitte den Entwickler kontaktieren 'mastodonautopost@l1am0.eu'`

**Comment by L1am0** [comment]
Hey scroom,

is the bug still there?
I solved a lot of problems in the last week.

If possible could you give me the whole error message?

**Comment by scroom** [comment]
The bug is solved! Thanks a lot for your great work!
