### ISSUE TITLE
No possibility to delete configuration

### ISSUE THREAD

**Issue by scroom** [L1am0/mastodon_wordpress_autopost#8]
There is (version 2.0.1) no possibility to delete a configuration and to restart the configuration. It would be great if that were possible.

In my case I've deleted Mastodon Autoshare of the list of authorized applications. It seems as well not possible to overwrite the settings.

**Comment by L1am0** [comment]
I don't get your issue.
It is possible to restart the whole setup process over and over again (did that during my testing of the plugin).

What does that have to do with the Mastodon Autoshare plugin? (Thats a different one)

**Comment by scroom** [comment]
Sorry for mixing up the names of the plugins. I've been testing both of them as I mentioned in another post. In fact I've retested the capability to delete the configuration and it worked. Sorry for disturbing!
