### ISSUE TITLE
toots in html format

### ISSUE THREAD

**Issue by svnet-libre** [L1am0/mastodon_wordpress_autopost#9]
Hi,
My wordpress posts are publishing on my mastodon account in html format
Toot example : 
`Revue de presse de l'April pour la semaine 5 de l'année 2018
<span style="font-style:italic;font-size:16px"><b>Article de</b> <a target="_blank" href="https://www.april.org/revue-de-presse-de-l-april-pour-la-semaine-5-de-l-annee-2018">echarpentier</a></span> <p>La <a target="_blank" href="http://www.april.org/revue-de-presse">revue de presse de l'April</a> est régulièrement ...
https://www.svnet.fr/revue-de-presse-de-lapril-pour-la-semaine-5-de-lannee-2018/
#SvnetActuLibre #LogicielsLibres`

**Comment by L1am0** [comment]
Thanks for that information!
I will change it to the excerpt. So it should be plain text only.
Will be in the next release. (Hope i have time for it on the weekend)

**Comment by L1am0** [comment]
It is fixed in verision 2.0.4

**Comment by svnet-libre** [comment]
It works

Great thanks
